In [50]:
import numpy as np
import pandas as pd

In [7]:
metro = pd.read_csv("../data/12_metro_compressor.csv")

In [10]:
metro.values

array([['2020-02-27 06:38:47', 9.3, -0.02, ..., 51.3, 6.04, '가동'],
       ['2020-02-27 07:28:21', 8.55, -0.02, ..., 56.8, 0.04, '정지'],
       ['2020-02-27 08:17:54', 8.67, -0.02, ..., 55.7, 0.03, '정지'],
       ...,
       ['2020-03-06 16:42:06', 9.74, -0.02, ..., 73.0, 3.77, '가동'],
       ['2020-03-06 17:31:39', 9.89, -0.02, ..., 72.5, 3.82, '가동'],
       ['2020-03-06 18:21:13', 9.87, -0.02, ..., 71.7, 3.75, '가동']],
      shape=(200, 7), dtype=object)

In [11]:
metro.columns

Index(['측정시각', '압축압력', '배출압력', '저장압력', '오일온도', '모터전류', '가동상태'], dtype='str')

In [13]:
metro.dtypes

측정시각        str
압축압력    float64
배출압력    float64
저장압력    float64
오일온도    float64
모터전류    float64
가동상태        str
dtype: object

In [15]:
metro.ndim

2

In [16]:
metro.size

1400

In [17]:
metro.shape

(200, 7)

In [18]:
metro.head

<bound method NDFrame.head of                     측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0    2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1    2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2    2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3    2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4    2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지
..                   ...   ...   ...   ...   ...   ...  ...
195  2020-03-06 15:03:00  8.72 -0.02  8.72  60.7  5.81   가동
196  2020-03-06 15:52:33  8.85 -0.02  8.85  61.9  0.04   정지
197  2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
198  2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
199  2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동

[200 rows x 7 columns]>

In [19]:
import os

In [21]:
os.getcwd()

'c:\\ex\\day14'

In [22]:
metro_comp=pd.read_csv("../data/12_metro_compressor.csv")

In [24]:
metro_comp.describe()

             압축압력        배출압력        저장압력        오일온도        모터전류
count  200.000000  200.000000  200.000000  199.000000  200.000000
mean     9.172200   -0.016950    9.171400   63.181910    2.060850
std      0.583699    0.047173    0.582497    6.249822    2.196505
min      8.130000   -0.030000    8.130000   50.100000    0.030000
25%      8.700000   -0.020000    8.697500   58.100000    0.040000
50%      9.175000   -0.020000    9.175000   62.900000    0.040000
75%      9.665000   -0.020000    9.655000   68.100000    3.812500
max     10.220000    0.600000   10.220000   75.000000    6.190000

In [26]:
metro_comp["오일온도"].isna()

0      False
1      False
2      False
3       True
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: 오일온도, Length: 200, dtype: bool

In [27]:
metro_comp["오일온도"].isna().sum()

np.int64(1)

In [28]:
metro_comp.shape

(200, 7)

In [45]:
metro_comp[['오일온도','가동상태']]

     오일온도 가동상태
0    51.3   가동
1    56.8   정지
2    55.7   정지
3     NaN   가동
4    55.3   정지
..    ...  ...
195  60.7   가동
196  61.9   정지
197  73.0   가동
198  72.5   가동
199  71.7   가동

[200 rows x 2 columns]

In [46]:
metro_comp.index

RangeIndex(start=0, stop=200, step=1)

In [48]:
metro_comp.set_index('측정시각')

                     압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
측정시각
2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지
...                   ...   ...   ...   ...   ...  ...
2020-03-06 15:03:00  8.72 -0.02  8.72  60.7  5.81   가동
2020-03-06 15:52:33  8.85 -0.02  8.85  61.9  0.04   정지
2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동

[200 rows x 6 columns]

In [58]:
metro_c = pd.read_csv("../data/12_metro_compressor__복사본.csv", header=None)

In [59]:
metro_c.head()

                 0     1     2     3     4     5   6
0  2020-02-27 6:38  9.30 -0.02  9.30  51.3  6.04  가동
1  2020-02-27 7:28  8.55 -0.02  8.55  56.8  0.04  정지
2  2020-02-27 8:17  8.67 -0.02  8.67  55.7  0.03  정지
3  2020-02-27 9:07  9.76 -0.02  9.76   NaN  3.81  가동
4  2020-02-27 9:57  8.49 -0.02  8.49  55.3  0.04  정지

In [60]:
metro_comp

                    측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0    2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1    2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2    2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3    2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4    2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지
..                   ...   ...   ...   ...   ...   ...  ...
195  2020-03-06 15:03:00  8.72 -0.02  8.72  60.7  5.81   가동
196  2020-03-06 15:52:33  8.85 -0.02  8.85  61.9  0.04   정지
197  2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
198  2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
199  2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동

[200 rows x 7 columns]

In [78]:
metro_comp[21:52]

                   측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
21  2020-02-28 00:41:13  8.22 -0.02  8.22  51.2  0.04   정지
22  2020-02-28 01:30:48  9.25 -0.02  9.25  52.0  0.04   정지
23  2020-02-28 02:20:21  8.40 -0.02  8.40  50.4  0.04   정지
24  2020-02-28 03:09:54  9.47 -0.02  9.47  51.0  0.04   정지
25  2020-02-28 03:59:28  8.60 -0.02  8.60  51.0  0.04   정지
26  2020-02-28 04:49:02  9.77 -0.02  9.77  50.5  3.84   가동
27  2020-02-28 05:38:37  8.42 -0.02  8.42  51.8  0.04   정지
28  2020-02-28 06:28:10  8.62 -0.02  8.62  53.7  0.04   정지
29  2020-02-28 07:17:45  8.75 -0.02  8.75  54.6  0.04   정지
30  2020-02-28 08:07:18  9.51 -0.02  9.51  57.9  3.71   가동
31  2020-02-28 08:56:53  8.33 -0.02  8.33  55.3  0.04   정지
32  2020-02-28 09:46:27  8.72 -0.02  8.73  56.8  0.04   정지
33  2020-02-28 10:36:00  9.16 -0.02  9.16  57.1  0.04   정지
34  2020-02-28 11:25:34  9.57 -0.02  9.57  57.6  3.78   가동
35  2020-02-28 12:15:08  8.32 -0.02  8.32  56.7  0.04   정지
36  2020-02-28 13:04:42  9.01 -0.02  9.02  57.5  0.04   정지
37  2020-02-28 13:54:16  8.49 -0.02  8.49  57.8  0.04   정지
38  2020-02-28 14:43:52  8.89 -0.02  8.90  58.5  0.04   정지
39  2020-02-28 15:33:25  8.18 -0.02  8.19  58.1  0.04   정지
40  2020-02-28 16:22:59  8.61 -0.02  8.61  56.9  0.04   정지
41  2020-02-28 17:12:32  9.34 -0.02  9.34  58.6  0.03   정지
42  2020-02-28 18:02:05  8.86 -0.02  8.86  58.5  0.04   정지
43  2020-02-28 18:51:39  8.80 -0.02  8.80  56.6  3.73   가동
44  2020-02-28 19:41:13  8.96 -0.02  8.96  57.4  0.04   정지
45  2020-02-28 20:30:46  8.18 -0.02  8.18  53.8  0.04   정지
46  2020-02-28 21:20:20  8.84 -0.02  8.84  55.5  0.04   정지
47  2020-02-28 22:09:55  9.39 -0.02  9.39  55.0  0.05   정지
48  2020-02-28 22:59:29  9.54 -0.02  9.53  53.2  6.05   가동
49  2020-02-28 23:49:02  8.49 -0.02  8.49  54.3  0.04   정지
50  2020-03-01 04:41:27  9.35 -0.03  9.35  66.3  3.79   가동
51  2020-03-01 05:31:01  8.20 -0.03  8.20  57.6  0.04   정지

In [79]:
from datetime import datetime

In [81]:
pd.to_datetime(metro_comp['측정시각'], format="%Y-%m-%d %H:%M:%S")

0     2020-02-27 06:38:47
1     2020-02-27 07:28:21
2     2020-02-27 08:17:54
3     2020-02-27 09:07:27
4     2020-02-27 09:57:01
              ...
195   2020-03-06 15:03:00
196   2020-03-06 15:52:33
197   2020-03-06 16:42:06
198   2020-03-06 17:31:39
199   2020-03-06 18:21:13
Name: 측정시각, Length: 200, dtype: datetime64[us]

In [82]:
metro_comp1=pd.read_csv("../data/12_metro_compressor.csv", usecols=['오일온도', '가동상태'])

In [83]:
metro_comp1

     오일온도 가동상태
0    51.3   가동
1    56.8   정지
2    55.7   정지
3     NaN   가동
4    55.3   정지
..    ...  ...
195  60.7   가동
196  61.9   정지
197  73.0   가동
198  72.5   가동
199  71.7   가동

[200 rows x 2 columns]

In [86]:
import numpy as np
import pandas as pd

In [89]:
semi= pd.read_csv("../data/12_metro_compressor_semicolon_복사본.csv", sep=";")

In [90]:
semi

                    측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0    2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1    2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2    2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3    2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4    2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지
..                   ...   ...   ...   ...   ...   ...  ...
195  2020-03-06 15:03:00  8.72 -0.02  8.72  60.7  5.81   가동
196  2020-03-06 15:52:33  8.85 -0.02  8.85  61.9  0.04   정지
197  2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
198  2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
199  2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동

[200 rows x 7 columns]

In [92]:
sem

                   측정시각;압축압력;배출압력;저장압력;오일온도;모터전류;가동상태
0      2020-02-27 06:38:47;9.3;-0.02;9.3;51.3;6.04;가동
1    2020-02-27 07:28:21;8.55;-0.02;8.55;56.8;0.04;정지
2    2020-02-27 08:17:54;8.67;-0.02;8.67;55.7;0.03;정지
3        2020-02-27 09:07:27;9.76;-0.02;9.76;;3.81;가동
4    2020-02-27 09:57:01;8.49;-0.02;8.49;55.3;0.04;정지
..                                                ...
195  2020-03-06 15:03:00;8.72;-0.02;8.72;60.7;5.81;가동
196  2020-03-06 15:52:33;8.85;-0.02;8.85;61.9;0.04;정지
197  2020-03-06 16:42:06;9.74;-0.02;9.74;73.0;3.77;가동
198  2020-03-06 17:31:39;9.89;-0.02;9.89;72.5;3.82;가동
199  2020-03-06 18:21:13;9.87;-0.02;9.87;71.7;3.75;가동

[200 rows x 1 columns]

In [96]:
pd.read_csv("../day12/인원조사.csv")

    이름    키  몸무게 성별
0  홍일동  166   45  여
1  홍이동  168   60  남
2  홍삼동  170   50  여
3  홍사동  172   55  남
4  홍오동  174   78  남

In [102]:
df_stud=pd.read_excel("../day12/인원조사 - 복사본.xlsx", sheet_name="Sheet2")

In [103]:
df_stud.to_csv('..//data//df_stud.csv', index=False)

In [106]:
semi= pd.read_csv("../data/12_metro_compressor_semicolon_복사본.csv", sep=";")

In [110]:
se = semi[['측정시각', '오일온도', '모터전류']][:51]

In [111]:
se.head(3)

                  측정시각  오일온도  모터전류
0  2020-02-27 06:38:47  51.3  6.04
1  2020-02-27 07:28:21  56.8  0.04
2  2020-02-27 08:17:54  55.7  0.03

In [112]:
metro_d=pd.read_csv('../data/12_metro_digital - 복사본.csv')

In [113]:
metro_d.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정시각    120 non-null    str
 1   압축기     120 non-null    int64
 2   타워      120 non-null    int64
 3   저압스위치   120 non-null    int64
dtypes: int64(3), str(1)
memory usage: 6.1 KB

In [114]:
metro_d.describe()

              압축기          타워  저압스위치
count  120.000000  120.000000  120.0
mean     0.908333    0.933333    0.0
std      0.289765    0.250490    0.0
min      0.000000    0.000000    0.0
25%      1.000000    1.000000    0.0
50%      1.000000    1.000000    0.0
75%      1.000000    1.000000    0.0
max      1.000000    1.000000    0.0

In [115]:
metro_d["압축기"]

0      0
1      1
2      1
3      1
4      1
      ..
115    1
116    1
117    1
118    1
119    1
Name: 압축기, Length: 120, dtype: int64

In [116]:
metro_d["압축기"].value_counts()

압축기
1    109
0     11
Name: count, dtype: int64

In [123]:
metro_d=pd.read_csv('../data/12_metro_digital - 복사본.csv', dtype={'압축기' : str})

In [124]:
metro_d.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정시각    120 non-null    str
 1   압축기     120 non-null    str
 2   타워      120 non-null    int64
 3   저압스위치   120 non-null    int64
dtypes: int64(2), str(2)
memory usage: 6.2 KB

In [125]:
metro_d["압축기"]

0      0
1      1
2      1
3      1
4      1
      ..
115    1
116    1
117    1
118    1
119    1
Name: 압축기, Length: 120, dtype: str

In [134]:
fe = pd.read_csv("../data/22_열처리 - 복사본.csv", usecols=['제어출력', '소입로온도'])[:50]

In [138]:
fe1 = pd.read_csv("../data/22_열처리 - 복사본.csv", usecols=['제어출력', '소입로온도'])

In [135]:
fe

     제어출력   소입로온도
0   0.426  861.05
1   0.463  860.99
2   0.438  861.05
3   0.445  861.05
4   0.421  861.11
5   0.428  861.11
6   0.405  861.18
7   0.443  861.11
8   0.419  861.18
9   0.423  861.18
10  0.424  861.19
11  0.409  861.25
12  0.417  861.25
13  0.393  861.31
14  0.401  861.31
15  0.409  861.31
16  0.387  861.38
17  0.394  861.38
18  0.402  861.38
19  0.410  861.38
20  0.387  861.44
21  0.395  861.44
22  0.372  861.50
23  0.381  861.50
24  0.388  861.50
25  0.395  861.50
26  0.373  861.56
27  0.351  861.62
28  0.389  861.56
29  0.366  861.62
30  0.401  861.56
31  0.377  861.62
32  0.378  861.64
33  0.385  861.64
34  0.361  861.70
35  0.398  861.64
36  0.374  861.70
37  0.381  861.70
38  0.387  861.70
39  0.392  861.70
40  0.397  861.70
41  0.350  861.82
42  0.386  861.76
43  0.390  861.76
44  0.395  861.76
45  0.368  861.82
46  0.402  861.76
47  0.406  861.76
48  0.381  861.82
49  0.414  861.76

In [132]:
fe.shape

(188, 2)

In [133]:
fe.std()

제어출력     0.176895
소입로온도    1.568289
dtype: float64

In [137]:
fe["제어출력"].isna().sum()

np.int64(0)

In [139]:
fe1["제어출력"].isna().sum()

np.int64(0)

In [140]:
fe1.info()

<class 'pandas.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제어출력    188 non-null    float64
 1   소입로온도   188 non-null    float64
dtypes: float64(2)
memory usage: 3.1 KB