In [1]:
import numpy as np

In [2]:
s = np.array([70, 72, 71, 95, 73])

In [3]:
np.median(s)

np.float64(72.0)

In [4]:
print(s.mean())

76.2

In [8]:
mat = np.array([[70,2.1], [72,2.3]])

In [9]:
print(mat.mean(axis=0))

[71.   2.2]

In [10]:
print(mat.mean(axis=1))

[36.05 37.15]

In [13]:
np.set_printoptions(precision=4, suppress=True, floatmode="fixed")

In [14]:
data = np.array([[4603, 2], [4967, 21],
[3632, 147], [58, 5]])

In [15]:
data.mean(axis=0)

array([3315.0000,   43.7500])

In [16]:
data.std(axis=0)

array([1942.7163,   60.0474])

In [19]:
np.round(data.var(axis=0),1)

array([3774146.5000,    3605.7000])

In [20]:
np.round(data.std(axis=0), 1)

array([1942.7000,   60.0000])

In [21]:
np.set_printoptions( precision=1, suppress=True, floatmode="fixed") # 소수점 이하 4자리 suppress=True, # 아주 작은 수는 과학적 표기 대신 0에 가깝게 floatmode="fixed" # 항상 고정 소수점으로 )

In [22]:
data.mean(axis=0)

array([3315.0,   43.8])

In [27]:
rpm = np.loadtxt('../data/10_mct_tool.csv',
    delimiter=',', 
    skiprows=1,     
    usecols=4)    
print(rpm.shape, rpm.dtype)

(40,) float64

In [28]:
type(rpm)

numpy.ndarray

In [29]:
rpm

array([4603.0, 4603.0, 4967.0, 4603.0, 4603.0, 4603.0, 4603.0, 4987.0,
       4603.0, 3632.0, 4603.0, 4603.0, 4603.0, 4603.0, 4603.0, 4603.0,
       4603.0, 4603.0, 4603.0, 4603.0,   58.0, 4603.0, 4603.0, 1216.0,
       4603.0, 4603.0, 1217.0, 4603.0, 4603.0, 4603.0, 4603.0, 4603.0,
       1241.0, 4603.0, 4603.0, 3143.0, 4603.0, 4967.0, 4603.0, 4987.0])

In [31]:
import pandas as pd

In [33]:
mct_df = pd.read_csv('../data/10_mct_tool.csv')

In [34]:
type(mct_df)

pandas.DataFrame

In [35]:
mct_df.head()

       공구번호  사이클타임  온도     전류   회전수  토크
0  43000007  21156  30  15.44  4603   2
1  43000007  15611  30  18.69  4603   2
2  43000007  15633  30  62.48  4967  21
3  43000007  15601  30  18.37  4603   2
4  43000007  15607  29  18.67  4603   3

In [36]:
mct_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   공구번호    40 non-null     int64
 1   사이클타임   40 non-null     int64
 2   온도      40 non-null     int64
 3   전류      40 non-null     float64
 4   회전수     40 non-null     int64
 5   토크      40 non-null     int64
dtypes: float64(1), int64(5)
memory usage: 2.0 KB

In [37]:
mct_df.columns

Index(['공구번호', '사이클타임', '온도', '전류', '회전수', '토크'], dtype='str')

In [39]:
mct_df["회전수"].values

array([4603, 4603, 4967, 4603, 4603, 4603, 4603, 4987, 4603, 3632, 4603,
       4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603,   58, 4603,
       4603, 1216, 4603, 4603, 1217, 4603, 4603, 4603, 4603, 4603, 1241,
       4603, 4603, 3143, 4603, 4967, 4603, 4987])

In [43]:
rpm = mct_df["회전수"].values

In [42]:
mct_df["회전수"].values.astype('float')

array([4603.0, 4603.0, 4967.0, 4603.0, 4603.0, 4603.0, 4603.0, 4987.0,
       4603.0, 3632.0, 4603.0, 4603.0, 4603.0, 4603.0, 4603.0, 4603.0,
       4603.0, 4603.0, 4603.0, 4603.0,   58.0, 4603.0, 4603.0, 1216.0,
       4603.0, 4603.0, 1217.0, 4603.0, 4603.0, 4603.0, 4603.0, 4603.0,
       1241.0, 4603.0, 4603.0, 3143.0, 4603.0, 4967.0, 4603.0, 4987.0])

In [45]:
import numpy as np

In [75]:
rpm = pd.read_csv('../data/10_mct_tool.csv')

In [76]:
rpm["회전수"].values

array([4603, 4603, 4967, 4603, 4603, 4603, 4603, 4987, 4603, 3632, 4603,
       4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603,   58, 4603,
       4603, 1216, 4603, 4603, 1217, 4603, 4603, 4603, 4603, 4603, 1241,
       4603, 4603, 3143, 4603, 4967, 4603, 4987])

In [77]:
print(rpm["회전수"].value_counts())

회전수
4603    30
4967     2
4987     2
3632     1
58       1
1216     1
1217     1
1241     1
3143     1
Name: count, dtype: int64

In [54]:
rpm["회전수"].mean()

np.float64(4212.625)

In [56]:
rpm["회전수"].std()

np.float64(1159.5254707455513)

In [57]:
rpm["회전수"].max()

np.int64(4987)

In [58]:
rpm["회전수"].min()

np.int64(58)

In [78]:
res = rpm.drop(rpm["회전수"].idxmin())["회전수"].values

In [79]:
res

array([4603, 4603, 4967, 4603, 4603, 4603, 4603, 4987, 4603, 3632, 4603,
       4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603,
       1216, 4603, 4603, 1217, 4603, 4603, 4603, 4603, 4603, 1241, 4603,
       4603, 3143, 4603, 4967, 4603, 4987])

In [84]:
res.std()

np.float64(943.6967281880867)

In [85]:
res.min()

np.int64(1216)

In [86]:
res.max()

np.int64(4987)

In [87]:
tq = pd.read_csv("../data/10_mct_tool - 복사.csv")

In [90]:
tq["토크"].values

array([  2,   2,  21,   2,   3,   2,   2,   3,   2, 147,   3,   2,   2,
         3,   2,   3,   3,   2,   2,   2,   5,   3,   3,   1,   2,   2,
         1,   3,   2,   3,   2,   2,   9,   2,   3, 146,   2,  21,   3,
         3])

In [94]:
high = tq["토크"][tq["토크"]>10]

In [95]:
print(high)

2      21
9     147
35    146
37     21
Name: 토크, dtype: int64

In [96]:
high.mean()

np.float64(83.75)

In [99]:
len(high)

4

In [101]:
cle = pd.read_csv("../data/11_diecasting_series.csv")

In [104]:
cle.head()

   시점  사이클타임  실린더압력    주조압력    형체력
0   1   20.7  214.0  1037.0  258.0
1   2   20.6  214.0  1038.0  255.0
2   3   20.9  218.0  1053.0  259.0
3   4   20.9  218.0  1054.0  257.0
4   5   20.8  214.0  1038.0  255.0

In [105]:
cle.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시점      50 non-null     int64
 1   사이클타임   50 non-null     float64
 2   실린더압력   50 non-null     float64
 3   주조압력    50 non-null     float64
 4   형체력     50 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 2.1 KB

In [107]:
cle.describe()

             시점        사이클타임       실린더압력         주조압력         형체력
count  50.00000    50.000000   50.000000    50.000000   50.000000
mean   25.50000   201.210000  225.780000   820.540000  302.260000
std    14.57738   904.296107   44.796269   264.516595   56.983997
min     1.00000    20.600000  108.000000   255.000000  222.000000
25%    13.25000    20.900000  215.000000   595.250000  257.000000
50%    25.50000    22.600000  218.000000  1037.000000  258.000000
75%    37.75000    36.000000  265.000000  1052.000000  362.500000
max    50.00000  6170.000000  265.000000  1156.000000  382.000000

In [108]:
cle["사이클타임"]

0       20.7
1       20.6
2       20.9
3       20.9
4       20.8
5       20.9
6       20.8
7       20.9
8       20.8
9       20.9
10      20.9
11      20.7
12      20.7
13      20.8
14      20.6
15      20.8
16      20.7
17      21.2
18      21.1
19      21.4
20      21.3
21      22.6
22      22.6
23      22.4
24      37.0
25      34.0
26      33.9
27      33.8
28      33.9
29      34.0
30      36.1
31      36.1
32      36.0
33      35.8
34      36.0
35      35.9
36      35.8
37      35.9
38      36.1
39      36.1
40      36.0
41      36.2
42     652.3
43      21.3
44      21.6
45      91.2
46      38.1
47    1885.3
48      36.1
49    6170.0
Name: 사이클타임, dtype: float64

In [109]:
cle["사이클타임"].values

array([  20.7,   20.6,   20.9,   20.9,   20.8,   20.9,   20.8,   20.9,
         20.8,   20.9,   20.9,   20.7,   20.7,   20.8,   20.6,   20.8,
         20.7,   21.2,   21.1,   21.4,   21.3,   22.6,   22.6,   22.4,
         37.0,   34.0,   33.9,   33.8,   33.9,   34.0,   36.1,   36.1,
         36.0,   35.8,   36.0,   35.9,   35.8,   35.9,   36.1,   36.1,
         36.0,   36.2,  652.3,   21.3,   21.6,   91.2,   38.1, 1885.3,
         36.1, 6170.0])

In [ ]:
np.drop(cle["사이클타임"][])

In [110]:
vib = np.array([2.1, 6.1, 2.0, 5.8])

In [111]:
print(np.sort(vib))

[2.0 2.1 5.8 6.1]

In [114]:
cle = pd.read_csv("../data/11_diecasting_series.csv")

In [116]:
see = cle["시점"].values
prs = cle["실린더압력"].values

In [120]:
np.argmax(see)

np.int64(49)

In [119]:
np.argmax(prs)

np.int64(24)

In [121]:

target_cycle = see[49]


target_pressure = prs[24]

# ⑤ 실린더압력번호(시점)와 값을 함께 출력해 확인
print(f" 사이클(시점): {target_cycle}, 실린더압력: {target_pressure}")

 사이클(시점): 50, 실린더압력: 265.0

In [122]:
# diff

In [123]:
vib = np.array([2.0 , 2.1 , 2.2, 7.0 , 7.1])

In [124]:
np.diff(vib)

array([0.1, 0.1, 4.8, 0.1])

In [127]:
change = np.diff(vib)

In [128]:
np.argmax(change)

np.int64(2)