In [1]:
print("hi")

hi

In [2]:
import numpy as np
import pandas as pd

In [4]:
a = pd.read_csv("../data/13_diecasting_shot_복사본.csv")

In [6]:
a.columns

Index(['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급'], dtype='str')

In [12]:
one_c = a[["형체력","실린더압력"]]

In [13]:
two_c = a["형체력"]

In [11]:
list(a.columns)

['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급']

In [14]:
a

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [15]:
a.sort_values("형체력")

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
103  104  DIE-C-01    NaN     NaN     NaN    NaN    NaN   양품
104  105  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량

[200 rows x 8 columns]

In [16]:
a.sort_values("형체력", ascending=False)

       샷      설비ID  실린더압력   주조압력  사이클타임  비스킷두께    형체력 품질등급
171  172  DIE-A-01  265.0  595.0   36.1   17.0  384.0   양품
169  170  DIE-A-01  265.0  596.0   36.1   18.0  382.0   양품
166  167  DIE-B-01  264.0  595.0   35.9   18.0  382.0   양품
179  180  DIE-C-01  265.0  596.0   36.2   18.0  382.0   양품
168  169  DIE-A-01  265.0  596.0   36.1   18.0  382.0   양품
..   ...       ...    ...    ...    ...    ...    ...  ...
103  104  DIE-C-01    NaN    NaN    NaN    NaN    NaN   양품
104  105  DIE-A-01    NaN    NaN    NaN    NaN    NaN   양품
187  188  DIE-A-01    NaN    NaN    NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN    NaN    NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN    NaN    NaN    NaN    NaN   불량

[200 rows x 8 columns]

In [17]:
a_sorted_by_body=a.sort_values("형체력", ascending=False)

In [18]:
a_sorted_by_body.index[:4]

Index([171, 169, 166, 179], dtype='int64')

In [19]:
a_sorted_by_body.index[:4].to_list()

[171, 169, 166, 179]

In [20]:
b = pd.read_csv("../data/13_diecasting_small_복사본.csv")

In [24]:
b.loc[0]

샷               1
설비ID     DIE-B-02
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [26]:
b.iloc[0]

샷               1
설비ID     DIE-B-02
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [22]:
big = b.sort_values("형체력", ascending=False)

In [27]:
big.loc[0]

샷               1
설비ID     DIE-B-02
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [28]:
big.iloc[0]

샷              23
설비ID     DIE-B-01
실린더압력       265.0
주조압력        595.0
사이클타임        33.9
비스킷두께        19.0
형체력         359.0
품질등급           주의
Name: 22, dtype: object

In [23]:
big

     샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
22  23  DIE-B-01  265.0   595.0   33.9   19.0  359.0   주의
17  18  DIE-A-02  265.0   596.0   33.7   19.0  357.0   주의
27  28  DIE-C-01  265.0   595.0   33.8   19.0  355.0   주의
12  13  DIE-A-02  265.0   596.0   33.9   19.0  354.0   주의
19  20  DIE-A-01  216.0  1044.0   21.2   11.0  259.0   불량
0    1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
11  12  DIE-C-01  215.0  1038.0   20.9   11.0  258.0   양품
13  14  DIE-B-02  215.0  1039.0   20.9   11.0  258.0   양품
14  15  DIE-C-01  215.0  1041.0   21.3    4.0  258.0   불량
16  17  DIE-A-02  218.0  1054.0   21.0   11.0  258.0   양품
18  19  DIE-A-02  214.0  1038.0   20.8   11.0  257.0   양품
15  16  DIE-A-01  218.0  1053.0   20.8   12.0  257.0   양품
8    9  DIE-B-01  217.0  1052.0   20.6   11.0  257.0   양품
1    2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
21  22  DIE-B-01  218.0  1053.0   20.9   11.0  257.0   양품
20  21  DIE-C-01  214.0  1037.0   20.8   11.0  257.0   양품
26  27  DIE-C-01  217.0  1051.0   20.9   12.0  257.0   양품
23  24  DIE-A-01  214.0  1037.0   20.8   12.0  255.0   양품
25  26  DIE-A-01  218.0  1055.0   20.9   11.0  255.0   양품
24  25  DIE-A-02  219.0  1058.0   21.3    2.0  255.0   불량
28  29  DIE-B-02  218.0  1055.0   20.7   11.0  255.0   양품
7    8  DIE-C-01  235.0  1137.0   22.5    7.0  255.0   주의
6    7  DIE-B-02  217.0  1052.0   20.6   11.0  254.0   양품
3    4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
2    3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
5    6  DIE-A-02  217.0  1052.0   20.6   11.0  253.0   양품
29  30  DIE-A-02  218.0  1054.0   21.4    2.0  253.0   불량
10  11  DIE-A-01  215.0  1038.0   20.9   11.0  250.0   양품
9   10  DIE-C-01  214.0  1036.0   93.1   12.0  247.0   불량
4    5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [29]:
a.loc[0:4, ["실린더압력", "형체력"]]

   실린더압력    형체력
0  214.0  258.0
1  217.0  257.0
2  214.0  254.0
3  217.0  253.0
4  217.0  254.0

In [36]:
s = b.sort_values("샷", ascending=True)

TypeError: 'method' object is not subscriptable

In [38]:
s.loc[17:20, ["설비ID", "사이클타임", "품질등급"]]

        설비ID  사이클타임 품질등급
17  DIE-A-02   33.7   주의
18  DIE-A-02   20.8   양품
19  DIE-A-01   21.2   불량
20  DIE-C-01   20.8   양품

In [44]:
b_shot_index=b.set_index("샷")

In [52]:
b_shot_index.loc[[3,7,15],["설비ID", "비스킷두께", "품질등급"]]

        설비ID  비스킷두께 품질등급
샷
3   DIE-A-02   21.0   주의
7   DIE-B-02   11.0   양품
15  DIE-C-01    4.0   불량

In [53]:
b_2=b_shot_index.loc[[3,7,15],["설비ID", "비스킷두께", "품질등급"]]

In [61]:
b_2.loc[[7],["비스킷두께"]]

   비스킷두께
샷
7   11.0

In [55]:
b_2.index

Index([3, 7, 15], dtype='int64', name='샷')

In [59]:
b_2.loc[7,"비스킷두께"]

np.float64(11.0)

In [60]:
b_2.loc[[7,15],["설비ID","품질등급"]]

        설비ID 품질등급
샷
7   DIE-B-02   양품
15  DIE-C-01   불량

In [78]:
a.loc[0:9,["설비ID", "비스킷두께", "품질등급"]]

       설비ID  비스킷두께 품질등급
0  DIE-A-01   10.0   양품
1  DIE-B-01   11.0   양품
2  DIE-B-01   11.0   양품
3  DIE-B-02   11.0   양품
4  DIE-A-01   11.0   양품
5  DIE-A-01   11.0   양품
6  DIE-A-01   11.0   양품
7  DIE-A-01   11.0   양품
8  DIE-B-02   11.0   양품
9  DIE-A-01   12.0   양품

In [77]:
a.iloc[-5:]

       샷      설비ID  실린더압력   주조압력   사이클타임  비스킷두께    형체력 품질등급
195  196  DIE-A-01  264.0  594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0  595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0  255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0  595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0  525.0  6170.0   15.0  237.0   불량