In [1]:
import os

In [2]:
import pandas as pd

In [3]:
with open("인원조사.csv", "r") as f:
    print(f.read())

이름,키,몸무게,성별
홍일동,166,45,여
홍이동,168,60,남
홍삼동,170,50,여
홍사동,172,55,남
홍오동,174,78,남

In [5]:
pd.read_csv("인원조사.csv")

    이름    키  몸무게 성별
0  홍일동  166   45  여
1  홍이동  168   60  남
2  홍삼동  170   50  여
3  홍사동  172   55  남
4  홍오동  174   78  남

In [6]:
student_df = pd.read_csv("인원조사.csv")

In [7]:
student_df.describe()

                키        몸무게
count    5.000000   5.000000
mean   170.000000  57.600000
std      3.162278  12.700394
min    166.000000  45.000000
25%    168.000000  50.000000
50%    170.000000  55.000000
75%    172.000000  60.000000
max    174.000000  78.000000

In [10]:
student_df["키"].std()

np.float64(3.1622776601683795)

In [11]:
student_df["키"].var()

np.float64(10.0)

In [17]:
mc_df= pd.read_csv("C:/ex/data/10_mct_tool - 복사.csv")

In [19]:
mc_df.describe

<bound method NDFrame.describe of         공구번호  사이클타임  온도     전류   회전수   토크
0   43000007  21156  30  15.44  4603    2
1   43000007  15611  30  18.69  4603    2
2   43000007  15633  30  62.48  4967   21
3   43000007  15601  30  18.37  4603    2
4   43000007  15607  29  18.67  4603    3
5   43000007  15557  30  14.98  4603    2
6   43000007  15557  31  18.40  4603    2
7   43000007  15636  31  62.06  4987    3
8   43000007  15600  30  18.55  4603    2
9   43000007  15634  30  64.48  3632  147
10  43000007  21207  30  18.84  4603    3
11  43000007  15554  30  24.45  4603    2
12  43000007  15600  30  18.51  4603    2
13  43000007  15606  30  19.19  4603    3
14  43000007  15612  29  18.42  4603    2
15  43000007  15602  30  18.48  4603    3
16  43000007  15602  31  19.05  4603    3
17  43000007  15557  31  18.66  4603    2
18  43000007  15606  30  18.29  4603    2
19  43000007   2149  29  18.65  4603    2
20  43000007  21213  30  21.81    58    5
21  43000007  15601  30  18.45  4603    3
22  43000007  15606  30  18.47  4603    3
23  43000007  15611  30  23.74  1216    1
24  43000007  15559  29  15.00  4603    2
25  43000007  15607  30  18.37  4603    2
26  43000007  15608  31  17.85  1217    1
27  43000007  15602  31  18.97  4603    3
28  43000007  15557  30  15.71  4603    2
29  43000007   2154  29  19.04  4603    3
30  43000007  15605  30  18.48  4603    2
31  43000007  15605  30  18.48  4603    2
32  43000007  15610  30  36.33  1241    9
33  43000007  15600  29  15.03  4603    2
34  43000007  15607  29  19.17  4603    3
35  43000007  15634  30  46.43  3143  146
36  43000007  15558  31  17.09  4603    2
37  43000007  15631  31  40.92  4967   21
38  43000007  15603  30  18.45  4603    3
39  43000007   2223  30  20.85  4987    3>

In [21]:
mc_df["토크"].std()

np.float64(31.83627990121833)

In [ ]:
mc_df["토크"].var()

np.float64(1013.5487179487181)

In [23]:
mc_df["토크"]

0       2
1       2
2      21
3       2
4       3
5       2
6       2
7       3
8       2
9     147
10      3
11      2
12      2
13      3
14      2
15      3
16      3
17      2
18      2
19      2
20      5
21      3
22      3
23      1
24      2
25      2
26      1
27      3
28      2
29      3
30      2
31      2
32      9
33      2
34      3
35    146
36      2
37     21
38      3
39      3
Name: 토크, dtype: int64

In [25]:
mc_df.columns

Index(['공구번호', '사이클타임', '온도', '전류', '회전수', '토크'], dtype='str')

In [26]:
mc_df.values

array([[4.3000007e+07, 2.1156000e+04, 3.0000000e+01, 1.5440000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5611000e+04, 3.0000000e+01, 1.8690000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5633000e+04, 3.0000000e+01, 6.2480000e+01,
        4.9670000e+03, 2.1000000e+01],
       [4.3000007e+07, 1.5601000e+04, 3.0000000e+01, 1.8370000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 2.9000000e+01, 1.8670000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.0000000e+01, 1.4980000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.1000000e+01, 1.8400000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5636000e+04, 3.1000000e+01, 6.2060000e+01,
        4.9870000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 3.0000000e+01, 1.8550000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5634000e+04, 3.0000000e+01, 6.4480000e+01,
        3.6320000e+03, 1.4700000e+02],
       [4.3000007e+07, 2.1207000e+04, 3.0000000e+01, 1.8840000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5554000e+04, 3.0000000e+01, 2.4450000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 3.0000000e+01, 1.8510000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.9190000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5612000e+04, 2.9000000e+01, 1.8420000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.1000000e+01, 1.9050000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.1000000e+01, 1.8660000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.8290000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1490000e+03, 2.9000000e+01, 1.8650000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1213000e+04, 3.0000000e+01, 2.1810000e+01,
        5.8000000e+01, 5.0000000e+00],
       [4.3000007e+07, 1.5601000e+04, 3.0000000e+01, 1.8450000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.8470000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5611000e+04, 3.0000000e+01, 2.3740000e+01,
        1.2160000e+03, 1.0000000e+00],
       [4.3000007e+07, 1.5559000e+04, 2.9000000e+01, 1.5000000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 3.0000000e+01, 1.8370000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5608000e+04, 3.1000000e+01, 1.7850000e+01,
        1.2170000e+03, 1.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.1000000e+01, 1.8970000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.0000000e+01, 1.5710000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1540000e+03, 2.9000000e+01, 1.9040000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5605000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5605000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5610000e+04, 3.0000000e+01, 3.6330000e+01,
        1.2410000e+03, 9.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 2.9000000e+01, 1.5030000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 2.9000000e+01, 1.9170000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5634000e+04, 3.0000000e+01, 4.6430000e+01,
        3.1430000e+03, 1.4600000e+02],
       [4.3000007e+07, 1.5558000e+04, 3.1000000e+01, 1.7090000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5631000e+04, 3.1000000e+01, 4.0920000e+01,
        4.9670000e+03, 2.1000000e+01],
       [4.3000007e+07, 1.5603000e+04, 3.0000000e+01, 1.8450000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 2.2230000e+03, 3.0000000e+01, 2.0850000e+01,
        4.9870000e+03, 3.0000000e+00]])

In [27]:
mc_df.values.max()

np.float64(43000007.0)

In [28]:
mc_df.ndim

2

In [31]:
import numpy as np

In [32]:
np.array([[1,2,3],[1,2,3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [33]:
student_df

    이름    키  몸무게 성별
0  홍일동  166   45  여
1  홍이동  168   60  남
2  홍삼동  170   50  여
3  홍사동  172   55  남
4  홍오동  174   78  남

In [34]:
student_df.values

array([['홍일동', 166, 45, '여'],
       ['홍이동', 168, 60, '남'],
       ['홍삼동', 170, 50, '여'],
       ['홍사동', 172, 55, '남'],
       ['홍오동', 174, 78, '남']], dtype=object)

In [38]:
student_df.values[:,1:3]

array([[166, 45],
       [168, 60],
       [170, 50],
       [172, 55],
       [174, 78]], dtype=object)

In [39]:
student_df.value_counts

<bound method DataFrame.value_counts of     이름    키  몸무게 성별
0  홍일동  166   45  여
1  홍이동  168   60  남
2  홍삼동  170   50  여
3  홍사동  172   55  남
4  홍오동  174   78  남>

In [40]:
mc_df.values[:,1:3]

array([[21156.,    30.],
       [15611.,    30.],
       [15633.,    30.],
       [15601.,    30.],
       [15607.,    29.],
       [15557.,    30.],
       [15557.,    31.],
       [15636.,    31.],
       [15600.,    30.],
       [15634.,    30.],
       [21207.,    30.],
       [15554.,    30.],
       [15600.,    30.],
       [15606.,    30.],
       [15612.,    29.],
       [15602.,    30.],
       [15602.,    31.],
       [15557.,    31.],
       [15606.,    30.],
       [ 2149.,    29.],
       [21213.,    30.],
       [15601.,    30.],
       [15606.,    30.],
       [15611.,    30.],
       [15559.,    29.],
       [15607.,    30.],
       [15608.,    31.],
       [15602.,    31.],
       [15557.,    30.],
       [ 2154.,    29.],
       [15605.,    30.],
       [15605.,    30.],
       [15610.,    30.],
       [15600.,    29.],
       [15607.,    29.],
       [15634.,    30.],
       [15558.,    31.],
       [15631.,    31.],
       [15603.,    30.],
       [ 2223.,    30.]])

In [41]:
import numpy as np

In [43]:
np.array([1,2.5,6], dtype='int')

array([1, 2, 6])

In [44]:
np.array([5,10,20])

array([ 5, 10, 20])

In [47]:
temp_c = np.array([30,30,30,30,29,30])

In [52]:
print(temp_c * 1.8 + 32)

[86.  86.  86.  86.  84.2 86. ]

In [54]:
np.arange(1,5+1)

array([1, 2, 3, 4, 5])

In [56]:
import numpy as np
import pandas as pd

In [60]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [66]:
arr_id = np.array([[1,2,3], [4,5,6]])

In [68]:
arr_id

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr_id.ndim

2

In [63]:
np.zeros(())

array(0.)

In [69]:
arr_id = np.array([[1,2,3], [4,5,6], [1,2,3]])

In [71]:
arr_id.ndim

2

In [78]:
arr_3d = np.array([
    [
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]
    ]
])

In [72]:
arr_id.shape

(3, 3)

In [79]:
arr_3d.ndim

3

In [80]:
arr_3d[0][:,1:]

array([[2, 3],
       [2, 3],
       [2, 3]])

In [81]:
np.zeros(3)

array([0., 0., 0.])

In [82]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [84]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [85]:
arr_id = np.array([0,10,20,30,40,50,60,70])

In [86]:
print(arr_id)

[ 0 10 20 30 40 50 60 70]

In [87]:
i_id = np.array([0, 70])

In [ ]:
i_id = np.linspace(0,70,8)

In [89]:
print(i_id)

[ 0. 10. 20. 30. 40. 50. 60. 70.]

In [92]:
i_id=np.arange(0,80,10)

In [93]:
print(i_id)

[ 0 10 20 30 40 50 60 70]

In [94]:
np.round(np.linspace(0,70,4),2)

array([ 0.  , 23.33, 46.67, 70.  ])

In [99]:
jump = np.arange(0,40,5)

In [100]:
print(jump)

[ 0  5 10 15 20 25 30 35]

In [101]:
b = np.array([1,2,3])

In [102]:
b.astype("float")

array([1., 2., 3.])

In [104]:
b.dtype

dtype('int64')

In [105]:
data = np.array([[30, 15.44], [30, 18.69],
[30, 62.48], [30, 18.37]])

In [114]:
np.array({'온도':[30,30,30,30],'전류':[15.44, 18.69, 62.48, 18.37]})

array({'온도': [30, 30, 30, 30], '전류': [15.44, 18.69, 62.48, 18.37]},
      dtype=object)

In [107]:
data.dtype

dtype('float64')

In [108]:
data.ndim

2

In [109]:
data.size

8

In [110]:
data.shape

(4, 2)

In [116]:
ts_df=np.array({'온도':[30,30,30,30],'전류':[15.44, 18.69, 62.48, 18.37]})

In [118]:
ts_df

array({'온도': [30, 30, 30, 30], '전류': [15.44, 18.69, 62.48, 18.37]},
      dtype=object)

In [119]:
ts_df.dtype

dtype('O')

In [120]:
data = np.array([[30, 15.44], [30, 18.69],
[30, 62.48], [30, 18.37]])

In [121]:
data.dtype

dtype('float64')

In [122]:
f = data.astype("int")

In [123]:
print(f)

[[30 15]
 [30 18]
 [30 62]
 [30 18]]

In [124]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [125]:
np.arange(12).reshape((2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [129]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [130]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [131]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [132]:
np.arange(12).reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [133]:
np.arange(12).reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [134]:
np.arange(12).reshape((2,2,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [135]:
arr_2d=np.arange(12).reshape(3,-1)

In [136]:
arr_2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [137]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
ct = np.array([21156, 15611, 15633, 15601,
15607, 15557, 15557, 15636,
15600, 15634, 21207, 15554])

In [142]:
ct.reshape(3,4)

array([[21156, 15611, 15633, 15601],
       [15607, 15557, 15557, 15636],
       [15600, 15634, 21207, 15554]])

In [143]:
flat = np.array([30, 15.44, 4603, 30, 18.69, 4603,
30, 62.48, 4967, 30, 18.37, 4603])

In [145]:
b = flat.reshape(4,3)

In [146]:
b

array([[  30.  ,   15.44, 4603.  ],
       [  30.  ,   18.69, 4603.  ],
       [  30.  ,   62.48, 4967.  ],
       [  30.  ,   18.37, 4603.  ]])

In [152]:
b.flatten()

array([  30.  ,   15.44, 4603.  ,   30.  ,   18.69, 4603.  ,   30.  ,
         62.48, 4967.  ,   30.  ,   18.37, 4603.  ])

In [155]:
date = np.array([[70, 2.1], [72, 2.3]])

In [157]:
date.shape

(2, 2)

In [158]:
date[1,0]

np.float64(72.0)

In [159]:
rpm = np.array([4603, 4603, 58, 4603, 4603,
1216, 4603, 4603, 1217, 4603])

In [160]:
print(rpm[0], rpm[-1])

4603 4603

In [162]:
data = np.array([[4603, 2], [58, 5],
[1216, 1], [4967, 21]])

In [163]:
print(data[2])

[1216    1]

In [164]:
data[2]

array([1216,    1])

In [166]:
data[:,0:1]

array([[4603],
       [  58],
       [1216],
       [4967]])

In [174]:
rpm = np.array([4603, 4603, 58, 4603, 4603,
1216, 4603, 4603, 1217, 4603])

In [168]:
rpm.max

In [169]:
rpm.max()

np.int64(4603)

In [170]:
rpm.min()

np.int64(58)

In [173]:
a = rpm - rpm.min()

In [172]:
rpm

array([4545, 4545,    0, 4545, 4545, 1158, 4545, 4545, 1159, 4545])

In [176]:
b = (rpm.max() - rpm.min()) / a

C:\Users\usr\AppData\Local\Temp\ipykernel_4580\3184653889.py:1: RuntimeWarning: divide by zero encountered in divide
  b = (rpm.max() - rpm.min()) / a

In [177]:
print(b)

[1.         1.                inf 1.         1.         3.92487047
 1.         1.         3.92148404 1.        ]

In [178]:
p = (rpm - rpm.min()) / (rpm.max() - rpm.min())

In [182]:
print(np.round(p,2))

[1.   1.   0.   1.   1.   0.25 1.   1.   0.26 1.  ]

In [183]:
vals = np.array([70, 95, 71, 88, 73])
print(vals > 85)

[False  True False  True False]

In [192]:
vals = np.array([70, 95, 71, 88, 73])

In [191]:
vals[(vals>85)&(vals<90)]

array([88])

In [193]:
vals = np.array([70, 95, 71, 88, 73])

In [194]:
print(np.where(vals > 85, 1, 0))

[0 1 0 1 0]

In [195]:
vals = np.array([70, 95, 71, 88, 73])
print(vals[(vals > 70) & (vals < 90)])  

print(vals[(vals < 71) | (vals > 90)])

[71 88 73]
[70 95]

In [196]:
5 & 3

1

In [197]:
7 & 3

3

In [198]:
10 & 3

2

In [199]:
9 & 3

1

In [200]:
8 & 3

0

In [201]:
rpm = np.array([4603, 4603, 58, 4603, 4603,
1216, 4603, 4603, 1217, 4603])
tq  = np.array([2, 2, 21, 2, 3, 2, 2, 3, 2, 147])

In [207]:
print(rpm[rpm < 2000])

[  58 1216 1217]

In [206]:
print(rpm[(rpm < 2000) | (tq > 100)])

[  58 1216 1217 4603]

In [220]:
_peek=pd.read_csv("C:/ex/data/10_mct_tool - 복사.csv")

In [219]:
print(_peek)

        공구번호  사이클타임  온도     전류   회전수   토크
0   43000007  21156  30  15.44  4603    2
1   43000007  15611  30  18.69  4603    2
2   43000007  15633  30  62.48  4967   21
3   43000007  15601  30  18.37  4603    2
4   43000007  15607  29  18.67  4603    3
5   43000007  15557  30  14.98  4603    2
6   43000007  15557  31  18.40  4603    2
7   43000007  15636  31  62.06  4987    3
8   43000007  15600  30  18.55  4603    2
9   43000007  15634  30  64.48  3632  147
10  43000007  21207  30  18.84  4603    3
11  43000007  15554  30  24.45  4603    2
12  43000007  15600  30  18.51  4603    2
13  43000007  15606  30  19.19  4603    3
14  43000007  15612  29  18.42  4603    2
15  43000007  15602  30  18.48  4603    3
16  43000007  15602  31  19.05  4603    3
17  43000007  15557  31  18.66  4603    2
18  43000007  15606  30  18.29  4603    2
19  43000007   2149  29  18.65  4603    2
20  43000007  21213  30  21.81    58    5
21  43000007  15601  30  18.45  4603    3
22  43000007  15606  30  18.47  4603    3
23  43000007  15611  30  23.74  1216    1
24  43000007  15559  29  15.00  4603    2
25  43000007  15607  30  18.37  4603    2
26  43000007  15608  31  17.85  1217    1
27  43000007  15602  31  18.97  4603    3
28  43000007  15557  30  15.71  4603    2
29  43000007   2154  29  19.04  4603    3
30  43000007  15605  30  18.48  4603    2
31  43000007  15605  30  18.48  4603    2
32  43000007  15610  30  36.33  1241    9
33  43000007  15600  29  15.03  4603    2
34  43000007  15607  29  19.17  4603    3
35  43000007  15634  30  46.43  3143  146
36  43000007  15558  31  17.09  4603    2
37  43000007  15631  31  40.92  4967   21
38  43000007  15603  30  18.45  4603    3
39  43000007   2223  30  20.85  4987    3

In [210]:
_peek.values[1:,4]

array([4603., 4967., 4603., 4603., 4603., 4603., 4987., 4603., 3632.,
       4603., 4603., 4603., 4603., 4603., 4603., 4603., 4603., 4603.,
       4603.,   58., 4603., 4603., 1216., 4603., 4603., 1217., 4603.,
       4603., 4603., 4603., 4603., 1241., 4603., 4603., 3143., 4603.,
       4967., 4603., 4987.])

In [214]:
rpm_all=_peek.values[:,4]

In [215]:
rpm_all < 2000

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False])

In [213]:
bad = rpm_all < 2000

In [217]:
print(
    "전체 %d건중 이상 %d건 (%.1f%%)" % (rpm_all.size, bad.sum(
                
)

_IncompleteInputError: incomplete input (1494159028.py, line 4)

In [222]:
_peek=pd.read_csv("C:/ex/data/10_mct_tool - 복사.csv")

In [224]:
_peek.values

array([[4.3000007e+07, 2.1156000e+04, 3.0000000e+01, 1.5440000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5611000e+04, 3.0000000e+01, 1.8690000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5633000e+04, 3.0000000e+01, 6.2480000e+01,
        4.9670000e+03, 2.1000000e+01],
       [4.3000007e+07, 1.5601000e+04, 3.0000000e+01, 1.8370000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 2.9000000e+01, 1.8670000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.0000000e+01, 1.4980000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.1000000e+01, 1.8400000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5636000e+04, 3.1000000e+01, 6.2060000e+01,
        4.9870000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 3.0000000e+01, 1.8550000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5634000e+04, 3.0000000e+01, 6.4480000e+01,
        3.6320000e+03, 1.4700000e+02],
       [4.3000007e+07, 2.1207000e+04, 3.0000000e+01, 1.8840000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5554000e+04, 3.0000000e+01, 2.4450000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 3.0000000e+01, 1.8510000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.9190000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5612000e+04, 2.9000000e+01, 1.8420000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.1000000e+01, 1.9050000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.1000000e+01, 1.8660000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.8290000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1490000e+03, 2.9000000e+01, 1.8650000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1213000e+04, 3.0000000e+01, 2.1810000e+01,
        5.8000000e+01, 5.0000000e+00],
       [4.3000007e+07, 1.5601000e+04, 3.0000000e+01, 1.8450000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.8470000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5611000e+04, 3.0000000e+01, 2.3740000e+01,
        1.2160000e+03, 1.0000000e+00],
       [4.3000007e+07, 1.5559000e+04, 2.9000000e+01, 1.5000000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 3.0000000e+01, 1.8370000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5608000e+04, 3.1000000e+01, 1.7850000e+01,
        1.2170000e+03, 1.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.1000000e+01, 1.8970000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.0000000e+01, 1.5710000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1540000e+03, 2.9000000e+01, 1.9040000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5605000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5605000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5610000e+04, 3.0000000e+01, 3.6330000e+01,
        1.2410000e+03, 9.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 2.9000000e+01, 1.5030000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 2.9000000e+01, 1.9170000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5634000e+04, 3.0000000e+01, 4.6430000e+01,
        3.1430000e+03, 1.4600000e+02],
       [4.3000007e+07, 1.5558000e+04, 3.1000000e+01, 1.7090000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5631000e+04, 3.1000000e+01, 4.0920000e+01,
        4.9670000e+03, 2.1000000e+01],
       [4.3000007e+07, 1.5603000e+04, 3.0000000e+01, 1.8450000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 2.2230000e+03, 3.0000000e+01, 2.0850000e+01,
        4.9870000e+03, 3.0000000e+00]])

In [225]:
peek_df=pd.read_csv("C:/ex/data/10_mct_tool - 복사.csv")

In [226]:
peek_df.columns

Index(['공구번호', '사이클타임', '온도', '전류', '회전수', '토크'], dtype='str')

In [227]:
peek_df["회전수"]

0     4603
1     4603
2     4967
3     4603
4     4603
5     4603
6     4603
7     4987
8     4603
9     3632
10    4603
11    4603
12    4603
13    4603
14    4603
15    4603
16    4603
17    4603
18    4603
19    4603
20      58
21    4603
22    4603
23    1216
24    4603
25    4603
26    1217
27    4603
28    4603
29    4603
30    4603
31    4603
32    1241
33    4603
34    4603
35    3143
36    4603
37    4967
38    4603
39    4987
Name: 회전수, dtype: int64

In [228]:
peek_df["회전수"].values

array([4603, 4603, 4967, 4603, 4603, 4603, 4603, 4987, 4603, 3632, 4603,
       4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603, 4603,   58, 4603,
       4603, 1216, 4603, 4603, 1217, 4603, 4603, 4603, 4603, 4603, 1241,
       4603, 4603, 3143, 4603, 4967, 4603, 4987])

In [229]:
rpm=peek_df["회전수"].values

In [230]:
peek_df["전류"]

0     15.44
1     18.69
2     62.48
3     18.37
4     18.67
5     14.98
6     18.40
7     62.06
8     18.55
9     64.48
10    18.84
11    24.45
12    18.51
13    19.19
14    18.42
15    18.48
16    19.05
17    18.66
18    18.29
19    18.65
20    21.81
21    18.45
22    18.47
23    23.74
24    15.00
25    18.37
26    17.85
27    18.97
28    15.71
29    19.04
30    18.48
31    18.48
32    36.33
33    15.03
34    19.17
35    46.43
36    17.09
37    40.92
38    18.45
39    20.85
Name: 전류, dtype: float64

In [231]:
amp=peek_df["전류"].values

In [233]:
(rpm<2000) | (amp > 100)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False])

In [234]:
peek_df.values[(rpm<2000) | (amp > 100)]

array([[4.3000007e+07, 2.1213000e+04, 3.0000000e+01, 2.1810000e+01,
        5.8000000e+01, 5.0000000e+00],
       [4.3000007e+07, 1.5611000e+04, 3.0000000e+01, 2.3740000e+01,
        1.2160000e+03, 1.0000000e+00],
       [4.3000007e+07, 1.5608000e+04, 3.1000000e+01, 1.7850000e+01,
        1.2170000e+03, 1.0000000e+00],
       [4.3000007e+07, 1.5610000e+04, 3.0000000e+01, 3.6330000e+01,
        1.2410000e+03, 9.0000000e+00]])

In [236]:
peek_df[(peek_df['회전수'] < 2000) | (peek_df["전류"]>100)]

        공구번호  사이클타임  온도     전류   회전수  토크
20  43000007  21213  30  21.81    58   5
23  43000007  15611  30  23.74  1216   1
26  43000007  15608  31  17.85  1217   1
32  43000007  15610  30  36.33  1241   9

NameError: name 'arr_final' is not defined